main: main.o datadict.o db.o file.o tuple.o data.o list.o

data.o: data.c data.h

tuple.o: tuple.c tuple.h

file.o: file.c file.h conf.h

db.o: db.c db.h datadict.h

datadict.o: datadict.c datadict.h

#buf.o: buf.c buf.h

list.o: list.c list.h

